### ISSUE TITLE
Feature request: Setting to disable text/interface antialiasing (FT_LOAD_TARGET_MONO)

### ISSUE THREAD

**Issue by ToaKraka** [schombert/Project-Alice#961]
In the original *Victoria 2*, most of the in-game text is generated from image files to which blurring (antialiasing) has been applied. A modder who dislikes blurry text can easily eliminate it by (1) editing the pre-blurred image files in an image editor, or (2) editing the plaintext .fnt files to reference different image files that are not blurred (such as Arial16.tga).

In the current version of *Project Alice*, all of the in-game text is generated from TrueType font files to which blurring is applied in-game, and there is no way to stop the game from applying the blurring. Accordingly, I would like to request the addition of an option that allows users to stop the game from applying the blurring.

At a glance, it [appears](https://freetype.org/freetype2/docs/reference/ft2-glyph_retrieval.html#ft_load_target_xxx) that blurring can be removed pretty easily by using "FT_LOAD_TARGET_MONO" rather than "FT_LOAD_TARGET_NORMAL" in src/text/fonts.cpp. But I'm not much of a programmer, so I may be wrong.

**Comment by schombert** [comment]
Please use the feature requests section of our discord for things like this so that they can get more visibility and community feedback. In this particular case, the effect you are seeing is not caused by the freetype settings, it is caused by a compromise in our font rendering system: we get a large range of font sizes, including the map text, by rendering fonts via an intermediate sdf texture. As you will read in January's update, how we render the ui in general is being overhauled, so I don't expect to make any changes to how the existing ui system works as it would be mostly a waste of developer time.

**Comment by wxwisiasdf** [comment]
YES THIS MUST BE IMPLEMENTED ASAP
